version: '3.7'

services:
#  nginx:
#    image: nginx:1.17
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 8000:80
#    depends_on:
#      - backend

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: slowmail
      POSTGRES_PASSWORD: slowmail
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached
#  :TODO общий env между postgres и worker
  worker:
    build:
      context: .
      dockerfile: CeleryDockFile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: 'postgresql://slowmail:slowmail@postgres:5432/slowmail'
    command: celery -A app.core.celery_app worker --loglevel=DEBUG
    depends_on:
      - "redis"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    ports:
      - '8888:8888'
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: 'postgresql://slowmail:slowmail@postgres:5432/slowmail'
    depends_on:
      - "worker"
      - "postgres"
      - "redis"

volumes:
  db-data:
