version: '3.7'

services:
#  nginx:
#    image: nginx:1.17
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 8000:80
#    depends_on:
#      - backend

  redis:
    image: redis
    container_name: redis
    networks:
      - webnet
    ports:
      - 6379:6379

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: slowmail
      POSTGRES_PASSWORD: slowmail
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached
    networks:
      - webnet

  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: .
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: 'postgresql://slowmail:slowmail@postgres:5432/slowmail'
    depends_on:
      - redis
    command: celery --app=app.tasks worker --loglevel=DEBUG -Q main-queue -c 1
    networks:
      - webnet

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    ports:
      - '8888:8888'
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: 'postgresql://slowmail:slowmail@postgres:5432/slowmail'
    depends_on:
      - "mongo_service"
      - "worker"
      - "postgres"
      - "redis"
    networks:
      - webnet

  mongo_service:
    image: mongo
    container_name: mongo_storage
    environment:
      MONGO_INITDB_DATABASE: mongo_slowmail
      MONGO_INITDB_ROOT_USERNAME: slowmail
      MONGO_INITDB_ROOT_PASSWORD: slowmail
    ports:
      - '27017-27019:27017-27019'
    networks:
      - webnet

volumes:
  db-data:

networks:
  webnet: