version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: slowmail
      POSTGRES_PASSWORD: slowmail
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached
    networks:
      - webnet

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    ports:
      - '8888:8888'
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: 'postgresql://slowmail:slowmail@postgres:5432/slowmail'
    depends_on:
      - "mongo_service"
      - "postgres"
    networks:
      - webnet

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: npm start
    tty: true
    ports:
      - '3000:3000'
    networks:
      - webnet

  mongo_service:
    image: mongo
    container_name: mongo_storage
    environment:
      MONGO_INITDB_DATABASE: mongo_slowmail
      MONGO_INITDB_ROOT_USERNAME: slowmail
      MONGO_INITDB_ROOT_PASSWORD: slowmail
    ports:
      - '27017-27019:27017-27019'
    networks:
      - webnet

volumes:
  db-data:

networks:
  webnet:
